### ISSUE TITLE
how custom the article width to 100%? 

### ISSUE THREAD

**Issue by yyangdid** [vjeantet/hugo-theme-docport#20]
how custom the article width to 100%? 

i want full screen ，but i don't know how to do.

please teach me , thank you.

**Comment by vjeantet** [comment]
Hello @yyangdid ,

if you want to only display your article, without the left and right navbar, set the `hide` param in the frontmatter of your md file.

```yaml
---
title: A page without sidebar and toc
hide:
  - toc
  - nav
---
```

example : https://docport.netlify.app/examples/page-without-sidebar-and-toc/

Does it respond to your need ?

**Comment by yyangdid** [comment]
no, i want the toc and nav , like this:  (do we have that option?)

![Snipaste_2020-09-25_17-00-24](https://user-images.githubusercontent.com/10922667/94248358-f28cc600-ff50-11ea-8426-1346f8c9bd41.png)

**Comment by vjeantet** [comment]
Just create a `docport.css` file in `static/css/docport.css`
with this content 
```css
body header > *, body article,body footer > * {	max-width: 100%;}
```

And you will have the layout you are looking at.
