### ISSUE TITLE
about nav

### ISSUE THREAD

**Issue by yyangdid** [vjeantet/hugo-theme-docport#21]
Are there any options to achieve this effect?

![a](https://user-images.githubusercontent.com/10922667/94361658-a1173f00-00e8-11eb-9288-2851dd5fa5ed.png)

![d](https://user-images.githubusercontent.com/10922667/94361728-1f73e100-00e9-11eb-8129-84262e8dc28c.png)

**Comment by vjeantet** [comment]
Hello @yyangdid, add this to your static/css/docport.css

```css
article>aside .menu > li:not(.parent),article>aside .menu > li.parent > *:not(li) {
	display: none
}
```
